name: there_chad

description: Production Flutter Application

publish_to: 'none'

version: 1.0.0+1

# =====================================================
# ================= SDK VERSION ========================
# =====================================================

environment:
  sdk: '^3.12.0'

# =====================================================
# ================= DEPENDENCIES =======================
# =====================================================

dependencies:

  flutter:
    sdk: flutter

  # ================= NETWORK =================
  dio: ^5.7.0

  # ================= SOCKET =================
  socket_io_client: ^2.0.3+1

  # ================= STATE MANAGEMENT =================
  provider: ^6.1.2

  # ================= LOCAL STORAGE =================
  shared_preferences: ^2.3.2

  # ================= RESPONSIVE UI =================
  flutter_screenutil: ^5.9.3

  # ================= LOADING UI =================
  loading_animation_widget: ^1.2.1

  # ================= UTILS =================
  uuid: ^4.5.1

  # ================= SAFE JSON =================
  equatable: ^2.0.5

  # ================= LOGGING =================
  logger: ^2.4.0

  # ================= ICONS =================
  cupertino_icons: ^1.0.8

# =====================================================
# ================= DEV DEPENDENCIES ===================
# =====================================================

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# =====================================================
# ================= FLUTTER =============================
# =====================================================

flutter:

  uses-material-design: true
