dependencies:
  flutter:
    sdk: flutter

  # ================= NETWORK =================
  dio: ^5.7.0

  # ================= SOCKET =================
  socket_io_client: ^2.0.3+1

  # ================= STATE MANAGEMENT =================
  provider: ^6.1.2

  # ================= LOCAL STORAGE =================
  shared_preferences: ^2.3.2

  # ================= UI HELPERS =================
  flutter_screenutil: ^5.9.3

  # ================= LOADING / UX =================
  loading_animation_widget: ^1.2.1

  # ================= UTILS =================
  uuid: ^4.5.1
